namespace L2147;

public class Test {
    private static Solution solution = new();

    [Fact]
    public void NoArrangementTest() {
        MainTest(0, "");
        MainTest(0, "PPPP");
        MainTest(0, "PPPPS");
        MainTest(0, "SPPPP");
        MainTest(0, "S");
        MainTest(0, "SSS");
        MainTest(0, "SPPSS");
    }

    [Fact]
    public void SanityTest() {
        MainTest(3, "SSPPSPS");
        MainTest(1, "PPSPSP");
        MainTest(4, "PPPPSSSPPPPSPSPSPSPSP");
        MainTest(40, "SSSPSPSPSPPPPSSSPPPPSPSPSPSPSP");
        MainTest(442368, "SPSPSPSPPSPSPSPSPSPSPSPSPPSPSPSPSSPSPSPSPSPSPSPPPPSPSPSPSSPSPSSSSPSPPSPPSPSPSPSPSPSS");
        MainTest(732940655, "SPSPSPSPPSPSPSPSPSPSPSPSPPSPSPSPSSPSPSPSPSPSPSPPPPSPSPSPSSPSPSSSSPSPPSPPSPSPSPSPSPSSPSPSPSPPSPSPSPSPSPSPSPSPPSPSPSPSSPSPSPSPSPSPSPPPPSPSPSPSSPSPSSSSPSPPSPPSPSPSPSPSPSSPSPSPSPPSPSPSPSPSPSPSPSPPSPSPSPSSPSPSPSPSPSPSPPPPSPSPSPSSPSPSSSSPSPPSPPSPSPSPSPSPSSPSPSPSPPSPSPSPSPSPSPSPSPPSPSPSPSSPSPSPSPSPSPSPPPPSPSPSPSSPSPSSSSPSPPSPPSPSPSPSPSPSSPSPSPSPPSPSPSPSPSPSPSPSPPSPSPSPSSPSPSPSPSPSPSPPPPSPSPSPSSPSPSSSSPSPPSPPSPSPSPSPSPSSPSPSPSPPSPSPSPSPSPSPSPSPPSPSPSPSSPSPSPSPSPSPSPPPPSPSPSPSSPSPSSSSPSPPSPPSPSPSPSPSPSSPSPSPSPPSPSPSPSPSPSPSPSPPSPSPSPSSPSPSPSPSPSPSPPPPSPSPSPSSPSPSSSSPSPPSPPSPSPSPSPSPSS");
    }

    private void MainTest(int correct, string corridor) {
        Assert.Equal(correct, solution.NumberOfWays(corridor));
    }
}